<?php

namespace App\Admin\Extensions\Form;

use Encore\Admin\Form\Field;

class GaodeMap extends Field
{
    protected $view = 'Admin.Form.gaodemap.iframe';
    protected static $js = [
        '//webapi.amap.com/maps?v=1.4.11&key=f231be765ed0dfbe9d0c960ca03d2ded'
    ];
    public function render()
    {
        return parent::render(); // TODO: Change the autogenerated stub
    }

}